### ISSUE TITLE
What sha should I use to match cl-async pre-merge-uv

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/cl-async-future#5]
What sha should I use to match cl-async pre-merge-uv

**Comment by orthecreedence** [comment]
I think you want commit 4853864bcac97c95cbf1203b380473b646025b8d

**Comment by nightshade427** [comment]
Thanks testing now ;)

**Comment by nightshade427** [comment]
Worked like a charm! Thanks ;)
